# EDA project

#### CROMA STORE DATA

#### 1) Understanding problem / statement

I have the data for Croma strore which i have to analyse and want to stiudy about the consumer pattern and behaviour such that i can extract some meaningful insights from it and take necessary decisions in order to improve sales

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
customers=pd.read_csv('messy_customers.csv')
order_item=pd.read_csv('messy_order_items.csv')
orders=pd.read_csv('messy_orders.csv')
products=pd.read_csv('messy_products.csv')

In [6]:
customers

    customer_id customer_name       city signup_date
0         C0001    Customer_1      DELHI  2024-02-09
1         C0002    Customer_2      delhi  2025-04-20
2         C0003    Customer_3  Bangalore  2024-08-19
3         C0004    Customer_4       Pune  2023-08-08
4         C0005           NaN  Bengaluru  2024-03-04
..          ...           ...        ...         ...
515       C0391  Customer_391    Kolkata  2023-01-07
516       C0483  Customer_483      Delhi  2023-02-25
517       C0473  Customer_473  Bangalore  2023-12-05
518       C0417  Customer_417  Bangalore  2025-01-24
519       C0303  Customer_303    Kolkata  2024-03-23

[520 rows x 4 columns]

i have data of 520 customers with having unique ID , name , city and their signup date

In [9]:
customers[customers.duplicated(keep=False)]

    customer_id customer_name       city signup_date
13        C0014   Customer_14      delhi  2024-08-18
32        C0033   Customer_33     mumbai  2024-04-30
132       C0133  Customer_133     Mumbai  2025-05-10
155       C0156  Customer_156       Pune  2024-08-07
179       C0180  Customer_180        NaN  2025-01-16
217       C0218  Customer_218      delhi  2025-02-02
221       C0222  Customer_222  Hyderabad  2024-05-20
249       C0250  Customer_250     Mumbai  2024-12-31
293       C0294  Customer_294  Hyderabad  2023-09-12
302       C0303  Customer_303    Kolkata  2024-03-23
308       C0309  Customer_309    Kolkata  2025-05-09
390       C0391  Customer_391    Kolkata  2023-01-07
414       C0415  Customer_415    Kolkata  2025-04-05
416       C0417  Customer_417  Bangalore  2025-01-24
438       C0439  Customer_439  Hyderabad  2023-07-03
460       C0461  Customer_461    Chennai  2024-06-02
465       C0466  Customer_466     mumbai  2023-04-28
472       C0473  Customer_473  Bangalore  2023-12-05
482       C0483  Customer_483      Delhi  2023-02-25
497       C0498  Customer_498     Mumbai  2023-06-13
500       C0309  Customer_309    Kolkata  2025-05-09
501       C0014   Customer_14      delhi  2024-08-18
502       C0415  Customer_415    Kolkata  2025-04-05
503       C0033   Customer_33     mumbai  2024-04-30
504       C0461  Customer_461    Chennai  2024-06-02
505       C0156  Customer_156       Pune  2024-08-07
506       C0250  Customer_250     Mumbai  2024-12-31
507       C0218  Customer_218      delhi  2025-02-02
508       C0222  Customer_222  Hyderabad  2024-05-20
509       C0294  Customer_294  Hyderabad  2023-09-12
510       C0133  Customer_133     Mumbai  2025-05-10
511       C0466  Customer_466     mumbai  2023-04-28
512       C0439  Customer_439  Hyderabad  2023-07-03
513       C0180  Customer_180        NaN  2025-01-16
514       C0498  Customer_498     Mumbai  2023-06-13
515       C0391  Customer_391    Kolkata  2023-01-07
516       C0483  Customer_483      Delhi  2023-02-25
517       C0473  Customer_473  Bangalore  2023-12-05
518       C0417  Customer_417  Bangalore  2025-01-24
519       C0303  Customer_303    Kolkata  2024-03-23

customers table also have some duplicate values in my data so  i have to delete it in order to make analysis process better

In [10]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    520 non-null    str
 1   customer_name  492 non-null    str
 2   city           479 non-null    str
 3   signup_date    520 non-null    str
dtypes: str(4)
memory usage: 16.4 KB

i have a column as 3   signup_date    520 non-null    str  which is not in proper format so i hvae to conver it into pandas date time format
also in column customer name and city i have

In [11]:
customers.describe()

       customer_id customer_name       city signup_date
count          520           492        479         520
unique         500           472         11         379
top          C0014   Customer_14  Hyderabad  2023-06-15
freq             2             2         54           4

In [12]:
order_item

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [14]:
order_item[order_item.duplicated(keep=False)]

      order_item_id order_id product_id  quantity  unit_price
110             111   O01090       P018       0.0     41057.0
155             156   O00621       P020       1.0         NaN
158             159   O00727       P002       1.0     34931.0
196             197   O00301       P003       3.0     60818.0
275             276   O00571       P022       1.0     20373.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[100 rows x 5 columns]

In [15]:
order_item.info()

<class 'pandas.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  2050 non-null   int64
 1   order_id       2050 non-null   str
 2   product_id     2050 non-null   str
 3   quantity       1732 non-null   float64
 4   unit_price     1039 non-null   float64
dtypes: float64(2), int64(1), str(2)
memory usage: 80.2 KB

In [16]:
order_item.describe()

       order_item_id     quantity    unit_price
count    2050.000000  1732.000000   1039.000000
mean      999.866341     1.991339  44956.006737
std       576.435038     1.411120  24978.977806
min         1.000000     0.000000   1072.000000
25%       502.250000     1.000000  23987.000000
50%       998.500000     2.000000  43654.000000
75%      1499.750000     3.000000  65136.500000
max      2000.000000     4.000000  89980.000000

In [17]:
orders

     order_id customer_id  order_date    payment_method
0      O00001       C0058  09/05/2024  Cash on Delivery
1      O00002       C0410  2024-02-01               upi
2      O00003       C0429  13/04/2025              Cash
3      O00004       C0272  2024-02-25        Debit Card
4      O00005       C0411  04-26-2025       credit card
...       ...         ...         ...               ...
1235   O01078       C0222  03-15-2025  Cash on Delivery
1236   O00944       C0014  04-08-2024       credit card
1237   O00128       C0383  03-31-2025       Credit Card
1238   O00966       C0053  23/02/2024               upi
1239   O00313       C0428  12-21-2024  Cash on Delivery

[1240 rows x 4 columns]

In [18]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1240 non-null   str
 1   customer_id     1240 non-null   str
 2   order_date      1240 non-null   str
 3   payment_method  1095 non-null   str
dtypes: str(4)
memory usage: 38.9 KB

In [19]:
orders[orders.duplicated(keep=False)]

     order_id customer_id  order_date    payment_method
14     O00015       C0329  02/09/2024  Cash on Delivery
71     O00072       C0033  2024-01-06               UPI
116    O00117       C0061  04-07-2025               UPI
127    O00128       C0383  03-31-2025       Credit Card
140    O00141       C0217  13/10/2024        Debit Card
...       ...         ...         ...               ...
1235   O01078       C0222  03-15-2025  Cash on Delivery
1236   O00944       C0014  04-08-2024       credit card
1237   O00128       C0383  03-31-2025       Credit Card
1238   O00966       C0053  23/02/2024               upi
1239   O00313       C0428  12-21-2024  Cash on Delivery

[80 rows x 4 columns]

In [20]:
products

   product_id    product_name     category  base_price
0        P001  Lenovo IdeaPad       Tablet     28151.0
1        P002     Samsung Tab   Smartphone     68660.0
2        P003     HP Pavilion  Accessories         NaN
3        P004      Lenovo Tab       tablet         NaN
4        P005         OnePlus       Tablet         NaN
..        ...             ...          ...         ...
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

[90 rows x 4 columns]

In [21]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     str
 1   product_name  90 non-null     str
 2   category      90 non-null     str
 3   base_price    33 non-null     float64
dtypes: float64(1), str(3)
memory usage: 2.9 KB

In [22]:
products.describe()

         base_price
count     33.000000
mean   45047.454545
std    25654.215131
min     2571.000000
25%    27157.000000
50%    47453.000000
75%    68660.000000
max    84776.000000

In [23]:
products[products.duplicated(keep=False)]

   product_id    product_name     category  base_price
9        P010       iPhone 13  smart phone         NaN
16       P017        Keyboard   Smartphone         NaN
19       P020   Dell Inspiron   Smartphone         NaN
21       P022     Samsung Tab    Accessory         NaN
32       P033  Wireless Mouse       laptop     47453.0
51       P052    Xiaomi Redmi  smart phone         NaN
58       P059         OnePlus  Accessories         NaN
61       P062   Dell Inspiron       Tablet         NaN
71       P072   Dell Inspiron       Tablet         NaN
75       P076  Wireless Mouse    Accessory     15249.0
80       P076  Wireless Mouse    Accessory     15249.0
81       P062   Dell Inspiron       Tablet         NaN
82       P072   Dell Inspiron       Tablet         NaN
83       P017        Keyboard   Smartphone         NaN
84       P020   Dell Inspiron   Smartphone         NaN
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

#### 2) Pre-processing data

In [24]:
customers.drop_duplicates(inplace=True)

In [26]:
order_item.drop_duplicates(inplace=True)

In [27]:
orders.drop_duplicates(inplace=True)

In [28]:
products.drop_duplicates(inplace=True)

In [31]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [36]:
orders['order_date'] = pd.to_datetime(orders['order_date'],format='mixed')

#### 3) Handling Inconsistant Data

In [61]:
customers['city'] = customers['city'].str.title()

In [67]:
customers['city'] = customers['city'].replace({'Bangalore':'Bengaluru'}).copy()

In [76]:
products['category'] = products['category'].str.title()
products['category'] = products['category'].replace({"Accessory":"Accessories","Smart Phone":"Smartphone"})

In [89]:
orders['payment_method'] = orders['payment_method'].str.title()
orders['payment_method']= orders['payment_method'].replace({"Cash On Delivery":"Cash"})

#### 4) Handling missing values

In [41]:
customers.isnull().sum()

customer_id       0
customer_name    28
city             40
signup_date       0
dtype: int64

In [42]:
orders.isnull().sum()

order_id            0
customer_id         0
order_date          0
payment_method    141
dtype: int64

In [43]:
order_item.isnull().sum()

order_item_id      0
order_id           0
product_id         0
quantity         313
unit_price       990
dtype: int64

In [44]:
products.isnull().sum()

product_id       0
product_name     0
category         0
base_price      49
dtype: int64

In [47]:
orders['payment_method'] = orders['payment_method'].ffill().copy()

In [51]:
customers['city'] = customers['city'].bfill().copy()

In [55]:
products.groupby('category')['base_price'].mean()

category
Accessories    81129.000000
Accessory      38291.333333
Laptop         18574.000000
Smartphone     51432.250000
Tablet         37737.166667
laptop         63925.600000
smart phone    49194.200000
tablet         59514.000000
Name: base_price, dtype: float64